force-app/main/default/objects/Dynamic_Trigger__mdt/Dynamic_Trigger__mdt.object-meta.xml
<CustomObject>
    <description>Specify dynamic trigger classes</description>
    <label>Dynamic Trigger</label>
    <pluralLabel>Dynamic Triggers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Dynamic_Trigger__mdt/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Class name for the trigger</description>
    <label>Class Name</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dynamic_Trigger__mdt/fields/Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Object_Type__c</fullName>
    <description>Object type for the trigger</description>
    <label>Object Type</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dynamic_Trigger__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>10</defaultValue>
    <description>Priority order where lower number is the highest priority</description>
    <label>Priority</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TriggerExtensionSupport.cls
public with sharing class TriggerExtensionSupport {
    
    public static List<ITriggerExtension> getTriggerClasses(String objectType) 
    {
        List<Dynamic_Trigger__mdt> triggerSettings = 
            [Select Class_Name__c from Dynamic_Trigger__mdt 
            where Object_Type__c = :objectType
            Order By Priority__c Asc];
        List<ITriggerExtension> results = new List<ITriggerExtension>();

        for(Dynamic_Trigger__mdt setting: triggerSettings)
        {
            System.Type thetype = Type.forName(setting.Class_Name__c);
			if(thetype==null) thetype = Type.forName('',setting.Class_Name__c);	// Try resolving local class
			if(thetype!=null) 
            {
    			Object theobject = thetype.newInstance();
			    if(theobject instanceof ITriggerExtension) results.add((ITriggerExtension)theobject);
            }

        }
        return results;
    }
}